AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API to upload download and delete videos from S3 via Lambda

Parameters:
  ExistingBucketName:
    Type: String
    Description: The name of the existing S3 bucket to use.

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes:
        - 'image~1png'
        - 'image~1jpeg'
        - 'application~1octet-stream'

  VideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/java17-examples-1.0-SNAPSHOT.jar
      Handler: LambdaCronFunctions.HandlerVideoJava17
      Runtime: java17
      Description: Java function
      MemorySize: 2048
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref ExistingBucketName
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource: !Sub 'arn:aws:s3:::${ExistingBucketName}/*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}:*'

      Tracing: Active
      Events:
        PostVideoEvent:
          Type: Api
          Properties:
            Path: /video/{bucketName}/{fileName}
            Method: POST
            RestApiId:
              Ref: MyApi
        GetVideoEvent:
          Type: Api
          Properties:
            Path: /video/{bucketName}/{fileName}
            Method: GET
            RestApiId:
              Ref: MyApi
        DeleteVideoEvent:
          Type: Api
          Properties:
            Path: /video/{bucketName}/{fileName}
            Method: DELETE
            RestApiId:
              Ref: MyApi